# AUTOGENERATED! DO NOT EDIT! File to edit: Load pets model _ gradio.ipynb.

# %% auto 0
__all__ = ['learner', 'categories', 'image', 'label', 'examples', 'intf', 'is_cat', 'classify_image']

# %% Load pets model _ gradio.ipynb 1
from fastai.vision.all import *
import gradio as gr

# %% Load pets model _ gradio.ipynb 2
def is_cat(x):
    return x[0].isupper()

# %% Load pets model _ gradio.ipynb 4
learner = load_learner('model.pkl')

# %% Load pets model _ gradio.ipynb 6
categories = ('dog', 'cat')

def classify_image(img):
    pred, idx, probs = learner.predict(img)
    return dict(zip(categories, map(float, probs)))

# %% Load pets model _ gradio.ipynb 8
image = gr.Image(height=192, width=192)
label = gr.Label()

examples = ['dog.jpg', 'cat.jpg', 'dunno.jpg'] 

intf = gr.Interface(fn=classify_image,inputs=image,outputs=label, examples=examples)
intf.launch(inline=False)
